---
# Playbook: deploy_dask_services_no_handlers.yml

- name: Configure and start Dask Scheduler service on Host
  hosts: hostnode
  become: true
  tasks:
    - name: Create Dask scheduler systemd service file
      ansible.builtin.template:
        src: files/dask-scheduler.service.j2
        dest: /etc/systemd/system/dask-scheduler.service
        owner: root
        group: root
        mode: '0644'

    - name: Reload systemd daemon
      ansible.builtin.systemd:
        daemon_reload: yes

    - name: Ensure Dask scheduler service is enabled and running
      ansible.builtin.systemd:
        name: dask-scheduler
        state: started # Ensures it's running (starts if stopped)
        enabled: yes   # Ensures it starts on boot

    - name: Restart Dask scheduler service
      ansible.builtin.systemd:
        name: dask-scheduler
        state: restarted

- name: Configure and start Dask Worker services on Workers
  hosts: workers
  become: true
  vars:
    worker_data_mount_point: /data # Match the mount point from your disk setup
  tasks:
    - name: Ensure Dask worker scratch directory exists
      ansible.builtin.file:
        path: "{{ worker_data_mount_point }}/dask-worker-space"
        state: directory
        owner: root # Adjust ownership if dask worker runs as non-root
        group: root # Adjust ownership if dask worker runs as non-root
        mode: '0755'

    - name: Create Dask worker systemd service file
      ansible.builtin.template:
        src: files/dask-worker.service.j2 # Ensure this path is correct
        dest: /etc/systemd/system/dask-worker.service
        owner: root
        group: root
        mode: '0644'

    - name: Reload systemd daemon
      ansible.builtin.systemd:
        daemon_reload: yes

    - name: Ensure Dask worker service is enabled and running
      ansible.builtin.systemd:
        name: dask-worker
        state: started # Ensures it's running (starts if stopped)
        enabled: yes   # Ensures it starts on boot

    - name: Restart Dask worker service
      ansible.builtin.systemd:
        name: dask-worker
        state: restarted
