---
- name: Number of PDB files
  hosts: "{{ groups['workers'][0] }}"
  gather_facts: false
  tasks:
    - name: Count on the target file
      command: wc -l /home/almalinux/paths.txt
      register: wc_output
      ignore_errors: true

    - name: Save the result
      copy:
        content: |
          {{ wc_output.stdout if wc_output.rc == 0 else "File not found or error occurred" }}
        dest: ./.TOTAL_PDB_FILES
      delegate_to: localhost
      run_once: true

