- name: Set up firewall
  become: true
  become_user: root
  hosts: all
  tasks:
    - name: enable ufw
      ansible.builtin.shell: "echo y | ufw enable"

    - name: allow traffic from cluster hosts
      ansible.builtin.shell: "ufw allow from {{ item }}"
      loop: "{{ query('inventory_hostnames', 'all')  }}"

    - name: allow Prometheus access from all sources
      ansible.builtin.shell: "ufw allow 9090"

    - name: allow Grafana access from all sources
      ansible.builtin.shell: "ufw allow 3000"

    - name: allow Node Exporter access from all sources
      ansible.builtin.shell: "ufw allow 9100"

    - name: allow HTTP/HTTPS access for Prometheus and Grafana
      ansible.builtin.shell: |
        ufw allow 80
        ufw allow 443

    - name: allow SSH access
      ansible.builtin.shell: "ufw allow ssh"

    - name: allow S3 access
      ansible.builtin.shell: "ufw allow 9000"

    - name: allow Cons traffic
      ansible.builtin.shell: "ufw allow 9001" 

