- name: Ensure Python Prerequisites are installed
  hosts: all
  become: yes
  tasks:
    - name: Install Dask (Distributed Computing Framework)
      ansible.builtin.pip:
        name: dask[distributed]
        state: present

- name: Install Worker-Specific Python Packages
  hosts: workers
  become: yes
  tasks:
    - name: Install Requests (Data Handling)
      ansible.builtin.pip:
        name: requests
        state: present

- name: Install Host-Specific Python Packages
  hosts: hostnode
  become: yes
  tasks:
    - name: Install Flask (User Interface)
      ansible.builtin.pip:
        name: Flask
        state: present
