- name: Install Dependencies
  hosts: all
  become: yes
  tasks:
    - name: Install Python dependencies
      ansible.builtin.pip:
        name:
          - torch
          - transformers
          - pandas
          - pyarrow
          - numpy
          - "bokeh>=2.4.2,!=3.0.*"
        state: present
        executable: /usr/bin/pip3
        extra_args: --no-cache-dir --extra-index-url https://download.pytorch.org/whl/cpu

