- name: Ensure Python Prerequisites are installed
  hosts: all
  become: yes
  tasks:
    - name: Install Dask (Distributed Computing Framework) globally
      ansible.builtin.pip:
        name: dask[distributed]
        state: present

- name: Install Worker-Specific Python Packages Globally
  hosts: workers
  become: yes # Required for global pip install
  tasks:
    - name: Install Requests (Data Handling) globally
      ansible.builtin.pip:
        name: requests
        state: present

- name: Install Host-Specific Python Packages Globally
  hosts: hostnode
  become: yes # Required for global pip install
  tasks:
    - name: Install Flask (User Interface) globally
      ansible.builtin.pip:
        name: Flask
        state: present
