---
- name: Install Celery and Dependencies
  hosts: all  # Target host node and worker nodes
  become: true # Required for installing pip and potentially system-wide packages
  tasks:
    - name: Install Celery with Redis support using pip
      ansible.builtin.pip:
        name: celery[redis]
        state: present
