- name: Install Dependencies
  hosts: all
  become: yes
  tasks:
    - name: Install Python dependencies
      ansible.builtin.pip:
        name:
          - torch
          - transformers
          - numpy
        state: latest
        executable: /usr/bin/pip3
        extra_args: --no-cache-dir --extra-index-url https://download.pytorch.org/whl/cpu

