- name: Deploy Flask Web Application for Image Captioning
  hosts: hostnode # Target only the host node
  become: true    # Needed for package installation and creating dirs in /opt

  vars:
    webapp_base_dir: "/opt/comp0239_coursework/webapp"
    webapp_templates_dir: "{{ webapp_base_dir }}/templates"
    webapp_uploads_dir: "{{ webapp_base_dir }}/uploads"
    target_user: almalinux

    local_app_script: "./app.py"
    local_templates_dir: "./files"
    local_service_template: "./files/webapp.service.j2"

  tasks:
    - name: Create Webapp base and templates directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        owner: "{{ target_user }}"
        group: "{{ target_user }}"
        mode: '0755'
      loop:
        - "{{ webapp_base_dir }}"
        - "{{ webapp_templates_dir }}"

    - name: Create Uploads directory with group write permissions
      ansible.builtin.file:
        path: "{{ webapp_uploads_dir }}"
        state: directory
        owner: "{{ target_user }}"
        group: "{{ target_user }}"
        mode: '0775'

    - name: Copy Flask application script
      ansible.builtin.copy:
        src: "{{ local_app_script }}"
        dest: "{{ webapp_base_dir }}/app.py"
        owner: "{{ target_user }}"
        group: "{{ target_user }}"
        mode: '0755'

    - name: Copy HTML templates directory content
      ansible.builtin.copy:
        src: "{{ local_templates_dir }}/"
        dest: "{{ webapp_templates_dir }}/"
        owner: "{{ target_user }}"
        group: "{{ target_user }}"
        mode: '0644'

    - name: Copy webapp systemd service file
      ansible.builtin.template:
        src: "{{ local_service_template }}"
        dest: /etc/systemd/system/webapp.service
        owner: root
        group: root
        mode: '0644'

    - name: Reload systemd daemon
      ansible.builtin.systemd:
        daemon_reload: yes

    - name: Ensure webapp service is enabled and started
      ansible.builtin.systemd:
        name: webapp
        state: started
        enabled: yes

    - name: Restart webapp service
      ansible.builtin.systemd:
        name: webapp
        state: restarted