---
- name: .miniopass
  hosts: storagenode
  become: yes
  gather_facts: no

  tasks:
    - name: Capture the contents of .miniopass
      ansible.builtin.command: cat /home/almalinux/.miniopass
      register: miniopass_contents

    - name: Password of Minio is
      ansible.builtin.debug:
        var: miniopass_contents.stdout

