---
- name: Install and unpack Foldclass CATH dataset
  hosts: workers
  tasks:
    - name: Create data directory
      ansible.builtin.file:
        path: /home/almalinux/data
        state: directory
        mode: '0755'

    - name: Download Foldclass CATH dataset
      ansible.builtin.get_url:
        dest: /home/almalinux/data/cath_foldclassdb.tar.gz
        url: "http://bioinfadmin.cs.ucl.ac.uk/downloads/merizo_search/cath_foldclassdb.tar.gz"
        tmp_dest: data/

    - name: Create unpack directory
      ansible.builtin.file:
        path: /home/almalinux/data/cath_foldclassdb/
        state: directory

    - name: Unpack Foldclass CATH dataset
      ansible.builtin.unarchive:
        dest: /home/almalinux/data/cath_foldclassdb/
        remote_src: true
        src: /home/almalinux/data/cath_foldclassdb.tar.gz

#    - name: Remove the source archive after unpacking
#      ansible.builtin.file:
#        path: /home/almalinux/data/cath_foldclassdb.tar.gz
#        state: absent
